apiVersion: v1
kind: Service
metadata:
  name:
     hello-world-backend
   spec:
     selector:
       app: hello-world-backend
     ports:
       - name: http
         port: 80
         targetPort: 4000
